version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: siem-postgres
    environment:
      POSTGRES_USER: siemuser
      POSTGRES_PASSWORD: siempassword
      POSTGRES_DB: siemdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
  grafana:
    image: grafana/grafana:latest
    container_name: siem-grafana
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

volumes:
  postgres-data:
  grafana-data: